<?php
	$sql = "SELECT ID, NAME, ICO_SLUG, CURRENT_PRICE, ICO_PRICE, START_DATE, END_DATE, DESCRIPTION, POTENTIAL_ROI, INVEST, ICO_QTY, WALLET, PROFIT, PER_FROM_WALLET, ICO_PROFIT_PER FROM ico_data WHERE ICO_STATUS=1 AND IS_VISIBLE=1";
	$result = $conn->query($sql);
	$dataArray = array();
?>